// <auto-generated />
using System;
using Gym_App;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gym_App.Migrations
{
    [DbContext(typeof(DbBase))]
    [Migration("20250926103943_Usersmigration")]
    partial class Usersmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gym_App.Domain.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("subscriptionPlan")
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Gym_App.Domain.Entities.Coach", b =>
                {
                    b.HasBaseType("Gym_App.Domain.Entities.User");

                    b.Property<string>("Certifications")
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("Specialty")
                        .HasColumnType("varchar(100)");

                    b.ToTable("Users", t =>
                        {
                            t.Property("Certifications")
                                .HasColumnName("Coach_Certifications");

                            t.Property("ExperienceYears")
                                .HasColumnName("Coach_ExperienceYears");

                            t.Property("Specialty")
                                .HasColumnName("Coach_Specialty");
                        });

                    b.HasDiscriminator().HasValue("Coach");
                });

            modelBuilder.Entity("Gym_App.Domain.Entities.Doctor", b =>
                {
                    b.HasBaseType("Gym_App.Domain.Entities.User");

                    b.Property<string>("Certifications")
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("Specialty")
                        .HasColumnType("varchar(100)");

                    b.HasDiscriminator().HasValue("Doctor");
                });

            modelBuilder.Entity("Gym_App.Domain.Entities.Trainee", b =>
                {
                    b.HasBaseType("Gym_App.Domain.Entities.User");

                    b.Property<int?>("HeightCm")
                        .HasColumnType("int");

                    b.Property<int?>("WeightKg")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Trainee");
                });
#pragma warning restore 612, 618
        }
    }
}
