// <auto-generated />
using System;
using Gym_App;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gym_App.Migrations
{
    [DbContext(typeof(DbBase))]
    [Migration("20251012191904_quickChangetoNotification")]
    partial class quickChangetoNotification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChallengesUser", b =>
                {
                    b.Property<Guid>("ChallengesChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParticipantsUserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ChallengesChallengeId", "ParticipantsUserID");

                    b.HasIndex("ParticipantsUserID");

                    b.ToTable("ChallengesUser");
                });

            modelBuilder.Entity("ExerciseMuscles", b =>
                {
                    b.Property<Guid>("ExercisesExerciseID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MusclesID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ExercisesExerciseID", "MusclesID");

                    b.HasIndex("MusclesID");

                    b.ToTable("ExerciseMuscles");
                });

            modelBuilder.Entity("ExerciseWorkout", b =>
                {
                    b.Property<Guid>("ExercisesExerciseID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkoutsWorkoutID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ExercisesExerciseID", "WorkoutsWorkoutID");

                    b.HasIndex("WorkoutsWorkoutID");

                    b.ToTable("ExerciseWorkout");
                });

            modelBuilder.Entity("Gym_App.Domain.Entities.Challenges", b =>
                {
                    b.Property<Guid>("ChallengeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("ChallengeId");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("Gym_App.Domain.Entities.Exercise", b =>
                {
                    b.Property<Guid>("ExerciseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(8000)");

                    b.Property<string>("Difficulty")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Grip")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("varchar(500)");

                    b.HasKey("ExerciseID");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Gym_App.Domain.Entities.Feedback", b =>
                {
                    b.Property<Guid>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CaloriesBurned")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("FeedbackText")
                        .IsRequired()
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkoutID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FeedbackID");

                    b.HasIndex("UserID");

                    b.HasIndex("WorkoutID")
                        .IsUnique();

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("Gym_App.Domain.Entities.LiveFeedback", b =>
                {
                    b.Property<Guid>("LiveID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeedbackText")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LiveID");

                    b.HasIndex("UserID");

                    b.ToTable("LiveFeedbacks");
                });

            modelBuilder.Entity("Gym_App.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("varchar(5000)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<Guid>("SenderUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SessionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageID");

                    b.HasIndex("SenderUserID");

                    b.HasIndex("SessionID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Gym_App.Domain.Entities.Muscles", b =>
                {
                    b.Property<Guid>("MusclesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("MusclesID");

                    b.ToTable("Muscles");
                });

            modelBuilder.Entity("Gym_App.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NotificationID");

                    b.HasIndex("UserID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Gym_App.Domain.Entities.PastInjuries", b =>
                {
                    b.Property<Guid>("InjuryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("InjuryDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InjuryID");

                    b.HasIndex("UserID");

                    b.ToTable("PastInjuries");
                });

            modelBuilder.Entity("Gym_App.Domain.Entities.RefreshTokens", b =>
                {
                    b.Property<Guid>("RefreshTokenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RefreshTokenID");

                    b.HasIndex("UserID");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Gym_App.Domain.Entities.Schedule", b =>
                {
                    b.Property<Guid>("ScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ScheduleID");

                    b.HasIndex("UserID");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Gym_App.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasColumnType("varchar(21)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("SessionID");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Gym_App.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PaymentID");

                    b.HasIndex("UserID");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Gym_App.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Certifications")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<int?>("HeightCm")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Specialty")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<int?>("WeightKg")
                        .HasColumnType("int");

                    b.Property<bool>("isEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("subscriptionPlan")
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Gym_App.Domain.Entities.Workout", b =>
                {
                    b.Property<Guid>("WorkoutID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("ScheduleID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WorkoutID");

                    b.HasIndex("ScheduleID");

                    b.HasIndex("UserID");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("SessionUser", b =>
                {
                    b.Property<Guid>("SessionsSessionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsersUserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SessionsSessionID", "UsersUserID");

                    b.HasIndex("UsersUserID");

                    b.ToTable("SessionUser");
                });

            modelBuilder.Entity("ChallengesUser", b =>
                {
                    b.HasOne("Gym_App.Domain.Entities.Challenges", null)
                        .WithMany()
                        .HasForeignKey("ChallengesChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gym_App.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ParticipantsUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExerciseMuscles", b =>
                {
                    b.HasOne("Gym_App.Domain.Entities.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExercisesExerciseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gym_App.Domain.Entities.Muscles", null)
                        .WithMany()
                        .HasForeignKey("MusclesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExerciseWorkout", b =>
                {
                    b.HasOne("Gym_App.Domain.Entities.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExercisesExerciseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gym_App.Domain.Entities.Workout", null)
                        .WithMany()
                        .HasForeignKey("WorkoutsWorkoutID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gym_App.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("Gym_App.Domain.Entities.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gym_App.Domain.Entities.Workout", "Workout")
                        .WithOne("Feedback")
                        .HasForeignKey("Gym_App.Domain.Entities.Feedback", "WorkoutID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("Gym_App.Domain.Entities.LiveFeedback", b =>
                {
                    b.HasOne("Gym_App.Domain.Entities.User", "User")
                        .WithMany("LiveFeedbacks")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gym_App.Domain.Entities.Message", b =>
                {
                    b.HasOne("Gym_App.Domain.Entities.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gym_App.Domain.Entities.Session", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Gym_App.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Gym_App.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gym_App.Domain.Entities.PastInjuries", b =>
                {
                    b.HasOne("Gym_App.Domain.Entities.User", "User")
                        .WithMany("PastInjuries")
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gym_App.Domain.Entities.RefreshTokens", b =>
                {
                    b.HasOne("Gym_App.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gym_App.Domain.Entities.Schedule", b =>
                {
                    b.HasOne("Gym_App.Domain.Entities.User", "User")
                        .WithMany("Schedules")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gym_App.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Gym_App.Domain.Entities.User", null)
                        .WithMany("Transactions")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("Gym_App.Domain.Entities.Workout", b =>
                {
                    b.HasOne("Gym_App.Domain.Entities.Schedule", "Schedule")
                        .WithMany("Workouts")
                        .HasForeignKey("ScheduleID");

                    b.HasOne("Gym_App.Domain.Entities.User", "User")
                        .WithMany("Workouts")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SessionUser", b =>
                {
                    b.HasOne("Gym_App.Domain.Entities.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionsSessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gym_App.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gym_App.Domain.Entities.Schedule", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("Gym_App.Domain.Entities.Session", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Gym_App.Domain.Entities.User", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("LiveFeedbacks");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("PastInjuries");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Schedules");

                    b.Navigation("Transactions");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("Gym_App.Domain.Entities.Workout", b =>
                {
                    b.Navigation("Feedback");
                });
#pragma warning restore 612, 618
        }
    }
}
