name: Autmoatic Deploy Kawerk Backend

on:
  # workflow_dispatch:
  workflow_run:
    workflows: [".NET"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Publish backend
        run: |
          dotnet restore
          dotnet publish -c Release -o MAPSM-Prod

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            mkdir -p /root/MAPSM
            # Backup the uploads folder if it exists
            [ -d /root/MAPSM/MAPSM-Prod/Uploads ] && cp -r /root/MAPSM/MAPSM-Prod/Uploads /tmp/Uploads
            rm -rf /root/MAPSM/MAPSM-Prod
            
      - name: Upload files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "MAPSM-Prod"
          target: "/root/MAPSM/"
          
      - name: Return Upload folder
        run: |
          mv -v /tmp/Uploads /root/MAPSM/MAPSM-Prod/
          rm -rf /tmp/Uploads
      
      - name: Restart service
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo systemctl restart mapsm-backend
